eureka:
  instance:
    # 以IP注册到注册中心
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    # 服务的一些元数据信息
    metadata-map:
      VERSION: 0.11.0
  client:
    serviceUrl:
      # 注册中心地址，多个用逗号隔开
      defaultZone:  http://dev.hzero.org:8000/eureka
    registryFetchIntervalSeconds: 10
    disable-delta: true

spring:
  datasource:
    url: jdbc:mysql://db.hzero.org:3306/srm_source?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${SPRING_DATASOURCE_USERNAME:hzero}
    password: ${SPRING_DATASOURCE_PASSWORD:hzero}

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  #数据库下划线转驼峰配置
  configuration:
    mapUnderscoreToCamelCase: true

#choerodon:
#  resource:
#    pattern: /v1/*

# 日志配置
logging:
  level:
    org.hzero: ${LOG_LEVEL:debug}
    org.apache.ibatis: ${LOG_LEVEL:debug}
    io.choerodon: ${LOG_LEVEL:debug}
